# Generated by Django 5.2 on 2025-04-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_category_id_category_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='id_meal',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
